#define a version
macro (conan_cmake_version APPLICATION_DIR)
file (STRINGS "${APPLICATION_DIR}/version.txt" VERSION)

string(REPLACE "." ";" APP_VERSION_LIST ${VERSION})
list(GET APP_VERSION_LIST 0 APP_VERSION_MAJOR)
list(GET APP_VERSION_LIST 1 APP_VERSION_MINOR)
list(GET APP_VERSION_LIST 2 APP_VERSION_PATCH)

set(LIBVERSION ${APP_VERSION_MAJOR}.${APP_VERSION_MINOR}.${APP_VERSION_PATCH})

add_definitions(-DAPP_VERSION_MAJOR=${APP_VERSION_MAJOR})
add_definitions(-DAPP_VERSION_MINOR=${APP_VERSION_MINOR})
add_definitions(-DAPP_VERSION_PATCH=${APP_VERSION_PATCH})

set(APP_VERSION_BUILD_UNKNOWN 0xffffffff)
add_definitions(-DAPP_VERSION_BUILD_UNKNOWN=${APP_VERSION_BUILD_UNKNOWN})

message("Version aquired from: ${APPLICATION_DIR}/version.txt")
if(NOT DEFINED BUILD_NUMBER)	
	message("${PROJECT_NAME} version is: ${VERSION}")
	add_definitions(-DAPP_VERSION_BUILD=${APP_VERSION_BUILD_UNKNOWN})
else()
	message("${PROJECT_NAME} version is: ${VERSION} (build: ${BUILD_NUMBER})")
	add_definitions(-DAPP_VERSION_BUILD=${BUILD_NUMBER})
endif(NOT DEFINED BUILD_NUMBER)

set(LIBSOVERSION ${APP_VERSION_MAJOR})
endmacro()